"""完善党建业务数据库模型

Revision ID: 7b840677f9ce
Revises: 5df8492f4faf
Create Date: 2026-03-05 07:37:29.645677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b840677f9ce'
down_revision: Union[str, Sequence[str], None] = '5df8492f4faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_categories',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='分类代码'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_knowledge_category_code', 'knowledge_categories', ['code'], unique=False)
    op.create_index('idx_knowledge_category_order', 'knowledge_categories', ['order'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='文档标题'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类代码'),
    sa.Column('file_path', sa.String(length=500), nullable=True, comment='文件路径'),
    sa.Column('file_type', sa.String(length=20), nullable=True, comment='文件类型（PDF/Word/TXT）'),
    sa.Column('chunk_count', sa.Integer(), nullable=True, comment='分块数量'),
    sa.Column('vector_collection', sa.String(length=100), nullable=True, comment='向量集合名称'),
    sa.Column('doc_metadata', sa.Text(), nullable=True, comment='元数据（JSON）- 发布时间、文号、关键词等'),
    sa.Column('uploaded_by', mysql.CHAR(length=36), nullable=True, comment='上传者ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_doc_category', 'knowledge_documents', ['category'], unique=False)
    op.create_index('idx_knowledge_doc_title', 'knowledge_documents', ['title'], unique=False)
    op.create_index('idx_knowledge_doc_type', 'knowledge_documents', ['file_type'], unique=False)
    op.create_table('party_fee_standards',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('member_id', mysql.CHAR(length=36), nullable=False, comment='党员ID'),
    sa.Column('monthly_income', sa.Numeric(precision=10, scale=2), nullable=False, comment='月收入'),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='应缴金额'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='生效日期'),
    sa.Column('branch_id', mysql.CHAR(length=36), nullable=True, comment='所属支部ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['member_id'], ['party_members.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fee_standard_effective', 'party_fee_standards', ['effective_date'], unique=False)
    op.create_index('idx_fee_standard_member', 'party_fee_standards', ['member_id'], unique=False)
    op.add_column('party_fees', sa.Column('collector', sa.String(length=100), nullable=True, comment='收款人'))
    op.add_column('party_fees', sa.Column('branch_id', mysql.CHAR(length=36), nullable=True, comment='所属支部ID'))
    op.create_index('idx_party_fee_branch_id', 'party_fees', ['branch_id'], unique=False)
    op.drop_index('idx_message_id', table_name='artifacts')
    op.create_index(op.f('ix_artifacts_message_id'), 'artifacts', ['message_id'], unique=False)
    op.drop_index('idx_category_id', table_name='common_tools')
    op.drop_index('idx_category_order', table_name='common_tools')
    op.drop_index('idx_visible', table_name='common_tools')
    op.create_index('idx_common_tool_category_order', 'common_tools', ['category_id', 'order'], unique=False)
    op.create_index(op.f('ix_common_tools_category_id'), 'common_tools', ['category_id'], unique=False)
    op.create_index(op.f('ix_common_tools_visible'), 'common_tools', ['visible'], unique=False)
    op.alter_column('course_categories', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='目录ID（UUID）',
               existing_nullable=False)
    op.alter_column('course_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='目录名称',
               existing_nullable=False)
    op.alter_column('course_categories', 'parent_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='父目录ID（NULL表示根目录）',
               existing_nullable=True)
    op.alter_column('course_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_categories', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_categories', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_parent_order', table_name='course_categories')
    op.create_index('idx_course_category_parent_order', 'course_categories', ['parent_id', 'order'], unique=False)
    op.create_index(op.f('ix_course_categories_parent_id'), 'course_categories', ['parent_id'], unique=False)
    op.drop_table_comment(
        'course_categories',
        existing_comment='文档目录表',
        schema=None
    )
    op.alter_column('course_documents', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='文档ID（UUID）',
               existing_nullable=False)
    op.alter_column('course_documents', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='文档标题',
               existing_nullable=False)
    op.alter_column('course_documents', 'summary',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment=None,
               existing_comment='文档摘要',
               existing_nullable=False)
    op.alter_column('course_documents', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='Markdown文件路径（相对于static目录）',
               existing_nullable=False)
    op.alter_column('course_documents', 'category_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='所属目录ID',
               existing_nullable=False)
    op.alter_column('course_documents', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_documents', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_documents', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_category_order', table_name='course_documents')
    op.create_index('idx_course_document_category_order', 'course_documents', ['category_id', 'order'], unique=False)
    op.create_index(op.f('ix_course_documents_category_id'), 'course_documents', ['category_id'], unique=False)
    op.drop_table_comment(
        'course_documents',
        existing_comment='文档表',
        schema=None
    )
    op.alter_column('messages', 'media_content',
               existing_type=mysql.TEXT(),
               comment='多模态内容JSON字符串',
               existing_comment='多模态内容JSON字符串（图片、音频、视频等）',
               existing_nullable=True)
    op.drop_index('idx_created_at', table_name='messages')
    op.drop_index('idx_session_id', table_name='messages')
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.add_column('organization_lives', sa.Column('meeting_type', sa.String(length=50), nullable=True, comment='会议类型（支部党员大会/支委会/党小组会/党课）'))
    op.add_column('organization_lives', sa.Column('host', sa.String(length=50), nullable=True, comment='主持人'))
    op.add_column('organization_lives', sa.Column('recorder', sa.String(length=50), nullable=True, comment='记录人'))
    op.add_column('organization_lives', sa.Column('expected_count', sa.Integer(), nullable=True, comment='应到人数'))
    op.add_column('organization_lives', sa.Column('absent_members', sa.Text(), nullable=True, comment='缺席人员（JSON）'))
    op.add_column('organization_lives', sa.Column('agenda', sa.Text(), nullable=True, comment='会议议程（JSON）'))
    op.add_column('organization_lives', sa.Column('resolutions', sa.Text(), nullable=True, comment='决议事项'))
    op.add_column('organization_lives', sa.Column('photos', sa.Text(), nullable=True, comment='活动照片（JSON数组）'))
    op.add_column('organization_lives', sa.Column('attachments', sa.Text(), nullable=True, comment='附件材料（JSON数组）'))
    op.add_column('organization_lives', sa.Column('branch_id', mysql.CHAR(length=36), nullable=True, comment='所属支部ID'))
    op.add_column('organization_lives', sa.Column('created_by', mysql.CHAR(length=36), nullable=True, comment='创建人ID'))
    op.alter_column('organization_lives', 'participants_count',
               existing_type=mysql.INTEGER(),
               comment='实到人数',
               existing_comment='参与人数',
               existing_nullable=False)
    op.create_index('idx_org_life_branch_id', 'organization_lives', ['branch_id'], unique=False)
    op.add_column('party_members', sa.Column('id_card', sa.String(length=18), nullable=True, comment='身份证号'))
    op.add_column('party_members', sa.Column('education', sa.String(length=20), nullable=True, comment='学历'))
    op.add_column('party_members', sa.Column('address', sa.String(length=500), nullable=True, comment='现居住地址'))
    op.add_column('party_members', sa.Column('work_unit', sa.String(length=200), nullable=True, comment='工作单位'))
    op.add_column('party_members', sa.Column('job_title', sa.String(length=100), nullable=True, comment='职务/职称'))
    op.add_column('party_members', sa.Column('application_date', sa.Date(), nullable=True, comment='入党申请书提交时间'))
    op.add_column('party_members', sa.Column('activist_date', sa.Date(), nullable=True, comment='确定为积极分子时间'))
    op.add_column('party_members', sa.Column('candidate_date', sa.Date(), nullable=True, comment='确定为发展对象时间'))
    op.add_column('party_members', sa.Column('provisional_date', sa.Date(), nullable=True, comment='接收为预备党员时间'))
    op.add_column('party_members', sa.Column('full_member_date', sa.Date(), nullable=True, comment='转正时间'))
    op.add_column('party_members', sa.Column('party_position', sa.String(length=100), nullable=True, comment='党内职务'))
    op.add_column('party_members', sa.Column('introducer_1', sa.String(length=50), nullable=True, comment='介绍人1'))
    op.add_column('party_members', sa.Column('introducer_2', sa.String(length=50), nullable=True, comment='介绍人2'))
    op.add_column('party_members', sa.Column('is_mobile', sa.Boolean(), nullable=False, comment='是否流动党员'))
    op.add_column('party_members', sa.Column('mobile_type', sa.String(length=20), nullable=True, comment='流动类型（流出/流入）'))
    op.add_column('party_members', sa.Column('mobile_reason', sa.String(length=500), nullable=True, comment='流动原因'))
    op.add_column('party_members', sa.Column('monthly_income', sa.Numeric(precision=10, scale=2), nullable=True, comment='月收入'))
    op.add_column('party_members', sa.Column('fee_standard', sa.Numeric(precision=10, scale=2), nullable=True, comment='党费标准（月缴金额）'))
    op.add_column('party_members', sa.Column('branch_id', mysql.CHAR(length=36), nullable=True, comment='所属支部ID'))
    op.create_index('idx_party_member_branch_id', 'party_members', ['branch_id'], unique=False)
    op.drop_index('idx_tool_id', table_name='sessions')
    op.drop_index('idx_updated_at', table_name='sessions')
    op.drop_index('idx_user_id', table_name='sessions')
    op.create_index(op.f('ix_sessions_tool_id'), 'sessions', ['tool_id'], unique=False)
    op.create_index(op.f('ix_sessions_updated_at'), 'sessions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_index('idx_order', table_name='tool_categories')
    op.create_index(op.f('ix_tool_categories_order'), 'tool_categories', ['order'], unique=False)
    op.drop_index('idx_is_admin', table_name='users')
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.alter_column('work_categories', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='分类ID（UUID）',
               existing_nullable=False)
    op.alter_column('work_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='分类名称',
               existing_nullable=False)
    op.alter_column('work_categories', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='分类图标（heroicons名称）',
               existing_nullable=True)
    op.alter_column('work_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('work_categories', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('work_categories', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_order', table_name='work_categories')
    op.create_index(op.f('ix_work_categories_order'), 'work_categories', ['order'], unique=False)
    op.drop_table_comment(
        'work_categories',
        existing_comment='作品分类表',
        schema=None
    )
    op.alter_column('works', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='作品ID（UUID）',
               existing_nullable=False)
    op.alter_column('works', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='作品名称',
               existing_nullable=False)
    op.alter_column('works', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment=None,
               existing_comment='作品描述',
               existing_nullable=False)
    op.alter_column('works', 'category_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='所属分类ID',
               existing_nullable=False)
    op.alter_column('works', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='图标标识（heroicons名称）',
               existing_nullable=True)
    op.alter_column('works', 'html_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='HTML文件路径（相对于static目录）',
               existing_nullable=False)
    op.alter_column('works', 'order',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('works', 'visible',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('works', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('works', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index('idx_category_order', table_name='works')
    op.drop_index('idx_visible', table_name='works')
    op.create_index('idx_work_category_order', 'works', ['category_id', 'order'], unique=False)
    op.create_index(op.f('ix_works_category_id'), 'works', ['category_id'], unique=False)
    op.create_index(op.f('ix_works_visible'), 'works', ['visible'], unique=False)
    op.drop_table_comment(
        'works',
        existing_comment='作品表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'works',
        '作品表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_works_visible'), table_name='works')
    op.drop_index(op.f('ix_works_category_id'), table_name='works')
    op.drop_index('idx_work_category_order', table_name='works')
    op.create_index('idx_visible', 'works', ['visible'], unique=False)
    op.create_index('idx_category_order', 'works', ['category_id', 'order'], unique=False)
    op.alter_column('works', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('works', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('works', 'visible',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否可见',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('works', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('works', 'html_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='HTML文件路径（相对于static目录）',
               existing_nullable=False)
    op.alter_column('works', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='图标标识（heroicons名称）',
               existing_nullable=True)
    op.alter_column('works', 'category_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='所属分类ID',
               existing_nullable=False)
    op.alter_column('works', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='作品描述',
               existing_nullable=False)
    op.alter_column('works', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='作品名称',
               existing_nullable=False)
    op.alter_column('works', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='作品ID（UUID）',
               existing_nullable=False)
    op.create_table_comment(
        'work_categories',
        '作品分类表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_work_categories_order'), table_name='work_categories')
    op.create_index('idx_order', 'work_categories', ['order'], unique=False)
    op.alter_column('work_categories', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('work_categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('work_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('work_categories', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='分类图标（heroicons名称）',
               existing_nullable=True)
    op.alter_column('work_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='分类名称',
               existing_nullable=False)
    op.alter_column('work_categories', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='分类ID（UUID）',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.create_index('idx_is_admin', 'users', ['is_admin'], unique=False)
    op.drop_index(op.f('ix_tool_categories_order'), table_name='tool_categories')
    op.create_index('idx_order', 'tool_categories', ['order'], unique=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_updated_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_tool_id'), table_name='sessions')
    op.create_index('idx_user_id', 'sessions', ['user_id'], unique=False)
    op.create_index('idx_updated_at', 'sessions', ['updated_at'], unique=False)
    op.create_index('idx_tool_id', 'sessions', ['tool_id'], unique=False)
    op.drop_index('idx_party_member_branch_id', table_name='party_members')
    op.drop_column('party_members', 'branch_id')
    op.drop_column('party_members', 'fee_standard')
    op.drop_column('party_members', 'monthly_income')
    op.drop_column('party_members', 'mobile_reason')
    op.drop_column('party_members', 'mobile_type')
    op.drop_column('party_members', 'is_mobile')
    op.drop_column('party_members', 'introducer_2')
    op.drop_column('party_members', 'introducer_1')
    op.drop_column('party_members', 'party_position')
    op.drop_column('party_members', 'full_member_date')
    op.drop_column('party_members', 'provisional_date')
    op.drop_column('party_members', 'candidate_date')
    op.drop_column('party_members', 'activist_date')
    op.drop_column('party_members', 'application_date')
    op.drop_column('party_members', 'job_title')
    op.drop_column('party_members', 'work_unit')
    op.drop_column('party_members', 'address')
    op.drop_column('party_members', 'education')
    op.drop_column('party_members', 'id_card')
    op.drop_index('idx_org_life_branch_id', table_name='organization_lives')
    op.alter_column('organization_lives', 'participants_count',
               existing_type=mysql.INTEGER(),
               comment='参与人数',
               existing_comment='实到人数',
               existing_nullable=False)
    op.drop_column('organization_lives', 'created_by')
    op.drop_column('organization_lives', 'branch_id')
    op.drop_column('organization_lives', 'attachments')
    op.drop_column('organization_lives', 'photos')
    op.drop_column('organization_lives', 'resolutions')
    op.drop_column('organization_lives', 'agenda')
    op.drop_column('organization_lives', 'absent_members')
    op.drop_column('organization_lives', 'expected_count')
    op.drop_column('organization_lives', 'recorder')
    op.drop_column('organization_lives', 'host')
    op.drop_column('organization_lives', 'meeting_type')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.create_index('idx_session_id', 'messages', ['session_id'], unique=False)
    op.create_index('idx_created_at', 'messages', ['created_at'], unique=False)
    op.alter_column('messages', 'media_content',
               existing_type=mysql.TEXT(),
               comment='多模态内容JSON字符串（图片、音频、视频等）',
               existing_comment='多模态内容JSON字符串',
               existing_nullable=True)
    op.create_table_comment(
        'course_documents',
        '文档表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_course_documents_category_id'), table_name='course_documents')
    op.drop_index('idx_course_document_category_order', table_name='course_documents')
    op.create_index('idx_category_order', 'course_documents', ['category_id', 'order'], unique=False)
    op.alter_column('course_documents', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('course_documents', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_documents', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_documents', 'category_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='所属目录ID',
               existing_nullable=False)
    op.alter_column('course_documents', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='Markdown文件路径（相对于static目录）',
               existing_nullable=False)
    op.alter_column('course_documents', 'summary',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               comment='文档摘要',
               existing_nullable=False)
    op.alter_column('course_documents', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               comment='文档标题',
               existing_nullable=False)
    op.alter_column('course_documents', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='文档ID（UUID）',
               existing_nullable=False)
    op.create_table_comment(
        'course_categories',
        '文档目录表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_course_categories_parent_id'), table_name='course_categories')
    op.drop_index('idx_course_category_parent_order', table_name='course_categories')
    op.create_index('idx_parent_order', 'course_categories', ['parent_id', 'order'], unique=False)
    op.alter_column('course_categories', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('course_categories', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_categories', 'order',
               existing_type=mysql.INTEGER(),
               comment='排序顺序',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('course_categories', 'parent_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='父目录ID（NULL表示根目录）',
               existing_nullable=True)
    op.alter_column('course_categories', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='目录名称',
               existing_nullable=False)
    op.alter_column('course_categories', 'id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='目录ID（UUID）',
               existing_nullable=False)
    op.drop_index(op.f('ix_common_tools_visible'), table_name='common_tools')
    op.drop_index(op.f('ix_common_tools_category_id'), table_name='common_tools')
    op.drop_index('idx_common_tool_category_order', table_name='common_tools')
    op.create_index('idx_visible', 'common_tools', ['visible'], unique=False)
    op.create_index('idx_category_order', 'common_tools', ['category_id', 'order'], unique=False)
    op.create_index('idx_category_id', 'common_tools', ['category_id'], unique=False)
    op.drop_index(op.f('ix_artifacts_message_id'), table_name='artifacts')
    op.create_index('idx_message_id', 'artifacts', ['message_id'], unique=False)
    op.drop_index('idx_party_fee_branch_id', table_name='party_fees')
    op.drop_column('party_fees', 'branch_id')
    op.drop_column('party_fees', 'collector')
    op.drop_index('idx_fee_standard_member', table_name='party_fee_standards')
    op.drop_index('idx_fee_standard_effective', table_name='party_fee_standards')
    op.drop_table('party_fee_standards')
    op.drop_index('idx_knowledge_doc_type', table_name='knowledge_documents')
    op.drop_index('idx_knowledge_doc_title', table_name='knowledge_documents')
    op.drop_index('idx_knowledge_doc_category', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('idx_knowledge_category_order', table_name='knowledge_categories')
    op.drop_index('idx_knowledge_category_code', table_name='knowledge_categories')
    op.drop_table('knowledge_categories')
    # ### end Alembic commands ###
